version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27020:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=pappyJ
      - MONGO_INITDB_ROOT_PASSWORD=brosjay
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=pappyJ
      - ME_CONFIG_MONGODB_ADMINPASSWORD=brosjay
      - ME_CONFIG_MONGODB_SERVER=mongodb
